### ISSUE TITLE
Picomotor Fixes

### ISSUE THREAD

**Issue by LiamDroog** [nfbeier/15tw-smartsystem#17]
- [x] 1. Documentation is needed for all classes and functions. Documentations should roughly follow docstring guidelines - https://www.programiz.com/python-programming/docstrings

- [x] 2. Line 18 of `MirrorControlWidget.py` needs to have correct pathing for `from SingleMirror_GUI import Ui_Form ` as it fails to import as is when instantiating a MirrorControlWidget

- [x] 3.  There should be error handling for the inputs passed to `MirrorControlWidget` ie, if xAxis or yAxis is non-integer or out of bounds, return the appropriate error message. Currently if you run it just dies and breaks everything unless you give it the right inputs.
- [x] same with movement commands, it should assert that the input axis and number of steps is correct (ie, if I give it a million steps then it should say no to prevent damage)
- [x] 4. There should be a function to prevent movement of the mirrors (even if buttons are pressed; check out button.setEnabled(true/false) such that when the laser is in high-power mode we cannot move the mirrors. This should be linked to a function along the lines of  `isMirrorSafeToFire` which returns true if the mirror cannot be moved and false if the mirror can be moved.
- [x] @nfbeier maybe you have thoughts on this, I think that instantiating the stages should happen within the widget, rather than passing the `self.stage1 = Newport.Picomotor8742(conn=0,multiaddr=True)` object into the `mirrorControlWidget`. That way you pass the stage as the integer (conn) arg and then the widget handles instantiating the `NewportPicotmotor...` stuff

**Comment by nfbeier** [comment]
I've made a branch for this issue @Hakeem098. It's directly linked to this issue

@LiamDroog As for your comment I don't think the stages should be initialized within the widget. Each widget corresponds to a single mirror that is controlled by two actuators. A single stage can control two mirrors. We have two options: keep the initialization as is to allow the widgets control of a single mirror, or redesign the widgets to control two mirrors while handling the initialization as you suggest. I don't see a strong argument to change the way the widgets are currently being used. We simply just pass in an initialized stage object with the corresponding actuator numbers. Let me know what you think.

**Comment by Hakeem098** [comment]
For issue number 4, how do you determine the laser high-power mode
condition for the mirrors?. Because I think I would need to pass that
condition to the button.setEnabled(true/false) .

**Comment by nfbeier** [comment]
@Hakeem098 the high power mode is a function called by pressing a button in the GUI. I would take a look at Liam's iris code for an example. The simplest solution to this would be to have a button that you press for "High power mode" that disables all of the buttons, and then a second press would turn it to "Alignment mode"

**Comment by nfbeier** [comment]
@Hakeem098 how's the progress on this issue? If the mirror control program is ready to go we can pull request your branch

**Comment by Hakeem098** [comment]
I have resolved all the issues. It is ready to be merged with Liam’s code

**Comment by nfbeier** [comment]
Okay, can you please open a pull request?

**Comment by nfbeier** [comment]
@Hakeem098 I'm adding functionality for the fourth mirror and consolidated the mirror objects into a list

**Comment by Hakeem098** [comment]
Alright. Thanks.
